### ISSUE TITLE
Add means to easily retrieve the shareid back from any call made to the servers

### ISSUE THREAD

**Issue by forceedge** [digitalanimal/advocate-things-js-sdk#10]
A call e.g AT.shareId() that will return the shareId and that can be used to do things

**Comment by nbrl** [comment]
It is `AT.sharepointToken` but it does need documenting/refining.

**Comment by forceedge** [comment]
Fixed as part of the documentation rewrite https://github.com/digitalanimal/advocate-things-js-sdk#other-available-data
