### ISSUE TITLE
A wrapper around the addeventlistener method

### ISSUE THREAD

**Issue by forceedge** [digitalanimal/advocate-things-js-sdk#11]
Something like AT.Attach('hover', element, function() {
    return _at: {
            touchpoint: 'banner-image-hover',
            user_id: '{{ user.id }}',
            email: '{{ user.email }}'
        }
});

That does this bit maybe

document.querySelector('#banner-img')
  .addEventListener('hover', function hoverListener() {
    AT.send({
        _at: {
            touchpoint: 'banner-image-hover',
            user_id: '{{ user.id }}',
            email: '{{ user.email }}'
        }
    });
  });

**Comment by nbrl** [comment]
I'd say that was outside the remit of the SDK and part of third-party implementation. The event listeners defined in the SDK are for Advocate Things events rather than for page-level JS events - i.e. for 'SharepointSaved' rather than 'hover'.

**Comment by forceedge** [comment]
Cool, so not appropriate for us to do this then?

**Comment by nbrl** [comment]
Not for the time being I don't think. Closing for now.
