### ISSUE TITLE
A method that adds the shareID to an anchor tag href maybe?

### ISSUE THREAD

**Issue by forceedge** [digitalanimal/advocate-things-js-sdk#12]
\<a id="sharer" href="shareme.php">Share link\</a>

So something like AT.Link('#sharer', 'ShareID');

This will append the shareid to the url

\<a id="sharer" href="shareme.php?ShareID={{ AT.shareID() }}">Share link\</a>

**Comment by nbrl** [comment]
Won't do it to an element, but storing the share tokens in a variable would be useful I think.
