### ISSUE TITLE
 TODO: do you think we should document the 'under the hood' props, e.g. `clientToken`, `{touch,share}point_url` etc.?

### ISSUE THREAD

**Issue by forceedge** [digitalanimal/advocate-things-js-sdk#14]
In the object_spec:

TODO: do you think we should document the 'under the hood' props, e.g. `clientToken`, `{touch,share}point_url` etc.?

**Comment by nbrl** [comment]
To keep the README as lean as we can, we probably don't want to document internal variables here. Any that *can* be defined by an SDK user should be documented, but e.g. clientToken can be left out as it's more of an implementation detail. @jabclab ?

**Comment by jabclab** [comment]
Yep, agreed. We want to try and strike that balance between giving enough and too much information. Therefore it makes sense not to document internal data properties as it is something a client/developer would not have to provide.

**Comment by nbrl** [comment]
Addressed by rewrite #18
