### ISSUE TITLE
[TODO] we should likely have an examples/ directory which could contain an example for universal_variable

### ISSUE THREAD

**Issue by forceedge** [digitalanimal/advocate-things-js-sdk#15]
In the object_spec of readme section:

[TODO] we should likely have an examples/ directory which could contain an example for universal_variable

**Comment by jabclab** [comment]
We may well have an explicit `examples/` directory soon but I think there are sufficient examples inline in the `README.md` for now. Agreed this issue can now be closed @forceedge ?

**Comment by forceedge** [comment]
Sure no probs mate.

**Comment by jabclab** [comment]
@forceedge :+1:
