### ISSUE TITLE
Ability to read client configuration on first implementation

### ISSUE THREAD

**Issue by forceedge** [digitalanimal/advocate-things-js-sdk#20]
A means to read/configurate a client just using the sdk in their page. This could be something like asking for client name etc and asking for sharepoints and touchpoints on the page.

Prototype already done by Zaid as bookmarklet.

**Comment by jabclab** [comment]
We could create this as a story in the backlog but it doesn't really belong in the SDK. Agreed @forceedge @zcrowe @nbrl ?

**Comment by zcrowe** [comment]
yes

**Comment by nbrl** [comment]
:+1:

**Comment by forceedge** [comment]
Agreed mate

**Comment by jabclab** [comment]
@zcrowe @nbrl @forceedge thanks guys, closing.
