### ISSUE TITLE
Share token URL rewrite causes tab titles to be rewritten to the URL in (at least) firefox

### ISSUE THREAD

**Issue by nbrl** [digitalanimal/advocate-things-js-sdk#29]
After URL rewrite (to add *e.g.* `?AT=123456`), the page title in a browser tab gets rewritten to be the new URL.

**Comment by jabclab** [comment]
Just need to set the second param at https://github.com/digitalanimal/advocate-things-js-sdk/blob/master/src/sdk.js#L266.
