### ISSUE TITLE
Consider Sharepoint tokens for when share buttons and BG advocacy enabled

### ISSUE THREAD

**Issue by nbrl** [digitalanimal/advocate-things-js-sdk#32]
At present, if there are buttons on a page and BG advocacy is enabled, the SPC will return one token for the page to use. This will always be added to the URL. If it is also used to populate buttons URLs (using e.g. `SharepointSaved` event listener, a visit from BG advocacy and visits via the button would appear to be the same.

**Comment by jabclab** [comment]
Closing as issue is captured in the DB. /cc @nbrl
