### ISSUE TITLE
Failed requests (i.e. 400s) result in JSON.parse error

### ISSUE THREAD

**Issue by nbrl** [digitalanimal/advocate-things-js-sdk#37]
400s return with no responseText for the XHR, so naturally JSON.parse('') or JSON.parse(undefined) fails.

Not a huge issue, but not very pleasant either.

**Comment by nbrl** [comment]
Mentioned in comments to non-merged PR #35

**Comment by nbrl** [comment]
Note this has not yet been solved.

**Comment by jabclab** [comment]
Closing as we have this pattern throughout the SDK now:

```js
xhr.onload = function () {
  if (!/^200$/.test(xhr.status)) {
    // handle error ...
    return;         
  }

  var data = JSON.parse(xhr.responseText);
  // etc.
```

i.e. we only attempt to `JSON.parse` the response if the request was deemed to be successful (and every successful request will provide an `application/json` response).
