### ISSUE TITLE
Older browsers do not support history rewrite

### ISSUE THREAD

**Issue by nbrl** [digitalanimal/advocate-things-js-sdk#42]
URL tracking requires history rewriting in a browser. Some browsers (IE7, Safari on Snow Leopard, WP?!) do not appear to support this.

Since there are a number of issues on [the library we are using](https://github.com/browserstate/history.js/) for this and that it has not been touched for a couple of years, I suspect that it might be worth writing a minimal helper ourselves, especially since we use a very minor subset of the functionality anyway.

**Comment by nbrl** [comment]
Just to point out that this does work, but will look weird in older browsers.

```
http://foo.com?foo=bar
http://foo.com#?foo=bar
```

**Comment by jabclab** [comment]
@nbrl Do you think there's anything we could do better if we were to write our own lib for this?

**Comment by nbrl** [comment]
Nope. Since the history api doesn't exist in the older browsers, the only work around is to use hash parameters as far as I know. Probably worth looking into but I can't think of another way at present.

**Comment by jabclab** [comment]
OK, in that case let's close the issue. It's likely `History.js` uses the accepted workaround. Happy to close @nbrl?

**Comment by nbrl** [comment]
Yep, closing. This may be revisited if we happen accross any of the issues in that repo, but until then I think it is fine.
