### ISSUE TITLE
Consider adding coverage reporting via coveralls.io

### ISSUE THREAD

**Issue by jabclab** [digitalanimal/advocate-things-js-sdk#44]
This is very easy to achieve using [istanbul](https://gotwarlost.github.io/istanbul/) but I imagine it would be pretty easy with Karma.

https://coveralls.io/

**Comment by nbrl** [comment]
Yep, coverage would be nice. I was using `karma-cover` (`istanbul` IIRC) briefly, but it is tricky since it is our built file that is tested, our coverage is invariably quite low with a lot of noise. I agree it is a useful reference, so I will add it, probably on the next PR.
