### ISSUE TITLE
If using fallback cookies, session storage and persistent storage will overwrite one another

### ISSUE THREAD

**Issue by nbrl** [digitalanimal/advocate-things-js-sdk#58]
`STORE_NAME` is used for all types of storage at present. This is fine in the case of localStorage/sessionStorage as they are two different stores, but where storage falls back to using cookies, the session storage cookies will overwrite the persistent cookies.

We should also look at setting an expiry for the session cookies.

**Comment by jabclab** [comment]
I don't think #55 addresses:

> We should also look at setting an expiry for the session cookies.

Do we want spawn another issue for this @nbrl ?

**Comment by nbrl** [comment]
We should, see #61.
