### ISSUE TITLE
Readme issues

### ISSUE THREAD

**Issue by forceedge** [digitalanimal/advocate-things-js-sdk#6]
Doesn't mention how to get an API key
Confusing part in Browser section "[TODO] I think this is ok as we the AT.send if clients want to do anything based on the DOM, e.g."

**Comment by forceedge** [comment]
Doesnt mention dependencies such as jQuery, it is obvious from the snippet but still a nice to have.

**Comment by forceedge** [comment]
The API url is outdated, decided against divshot, update to cloudfront url.

**Comment by forceedge** [comment]
Readme mentions the need to register with an "Advocay analyst" but doesn't say how or why

**Comment by forceedge** [comment]
Typo in Automatic section of Implementation. Reads "... In order to send metadata about these Touchpoints and Sharepoints you should defined a global advocate_things_data variable, e.g."

**Comment by forceedge** [comment]
The snippet needs to have a uniform way of showing variables to be replaced by the client.

**Comment by forceedge** [comment]
Anything that binds to a DOM element should be represented within a jQuery(document).ready(function{ ... }) in the snippets. Makes it more obvious and easier to implement i think

**Comment by forceedge** [comment]
NB the Advocate Things <script> tag must have been loaded prior to these actions taking place

The snippets after this line are:
1. document.querySelector('#banner-img')
This can potentially fail if the client is only looking for the script being pre-loaded, if this script is loaded before the DOM element, it will return false i think.

**Comment by forceedge** [comment]
Document the latest AT JSON spec e.g sharepoint_name => sharepointName

**Comment by forceedge** [comment]
Data Object Spec:

The optional parameters should have a comment of //Optional so someone could first try to implement with the bare minimum to make it just work.

**Comment by forceedge** [comment]
This readme is gonna get really long, maybe have an  index on top to easily navigate through the readme

**Comment by forceedge** [comment]
Add documentation about how to retrieve the shareId at any point and any other usefull methods provided by the sdk

**Comment by nbrl** [comment]
Should document callback and event listener arguments etc.

**Comment by forceedge** [comment]
@nbrl I am guessing all this is done due to the documentation rewrite?

**Comment by nbrl** [comment]
All addressed by rewrite.
