### ISSUE TITLE
CORS issue when posting data to sharepoint collector

### ISSUE THREAD

**Issue by forceedge** [digitalanimal/advocate-things-js-sdk#7]
POST https://sharepoint-data-collector.herokuapp.com/campaign/token/sharepoint/data
500 Internal Server Error
		70ms	

"NetworkError: 500 Internal Server Error - https://sharepoint-data-collector.herokuapp.com/campaign/token/sharepoint/data"
data

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sharepoint-data-collector.herokuapp.com/campaign/token/sharepoint/data. This can be fixed by moving the resource to the same domain or enabling CORS.

**Comment by jabclab** [comment]
Can this one be closed now post {T,S}DC changes? /cc @forceedge @nbrl

**Comment by nbrl** [comment]
I should think so - the only time I can think of that we get a 500 and CORS errors now is when the collectors are down. @forceedge ?

**Comment by forceedge** [comment]
@nbrl would'nt that result in a 404 rather than a 500?

**Comment by nbrl** [comment]
I think because the request is initially handled by the LB, it gets the response from the LB that "something isn't quite right."

**Comment by forceedge** [comment]
Ah right, i guess that can't be helped, well not atleast from the collectors. Will close this issue.
